[project]
name = "mushrooms-classification-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "AbdulrahmanSadik", email = "abdulrahmansadek00@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
    "streamlit>=1.64.0",
]

[project.scripts]
mushrooms-classification-project = "mushrooms_classification_project:main"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"
